### ISSUE TITLE
CM13 not work

### ISSUE THREAD

**Issue by Alexey71** [paphonbth/CMHeadsetIcon#1]
Hello does not work. The icon appears and immediately disappears
Xiaomi redmi note 3 pro -  cm13.0
https://drive.google.com/open?id=0B35Mew37y2a_NVFFTTE0cXJabDg
[xposed_error_20160705_095828.txt](https://github.com/paphonbth/CMHeadsetIcon/files/347202/xposed_error_20160705_095828.txt)

**Comment by Alexey71** [comment]
Any fix pls

**Comment by Alexey71** [comment]
Where are developer?

**Comment by suphon-t** [comment]
There are no error info in the log. Please attach logcat.

**Comment by Alexey71** [comment]
[logcat.zip](https://github.com/paphonbth/CMHeadsetIcon/files/366228/logcat.zip)

**Comment by Alexey71** [comment]
Hi. Any news?

**Comment by suphon-t** [comment]
What are your other module? There may be some conflicts.

**Comment by Alexey71** [comment]
I tried to disable all modules. Leaving only yours, it does not help

**Comment by Alexey71** [comment]
Hello. No test build?)

**Comment by Alexey71** [comment]
Is there anyone at all?
